services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - ./api:/app/api
      - ./database:/app/database
      - ./dataManagers:/app/dataManagers
      - ./xchanges:/app/xchanges
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    command: uvicorn load:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - internal-network
    expose:
      - "8000"


  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
    command: npm run dev -- --host 0.0.0.0
    networks:
      - internal-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - internal-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --appendfsync everysec --save "" --dir /data
    user: redis  # Using redis user instead of UID/GID

volumes:
  redis-data:
    driver: local

# Define a custom internal network
networks:
  internal-network:
    driver: bridge