"""add Linear Perpetual Table

Revision ID: 2feb6c33aa9a
Revises: 624df8e0e995
Create Date: 2024-11-02 17:51:10.796675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2feb6c33aa9a'
down_revision: Union[str, None] = '624df8e0e995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bybit_linear_perp_instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_coin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quote_coin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('launch_time', sa.Integer(), nullable=True),
    sa.Column('price_scale', sa.Integer(), nullable=False),
    sa.Column('funding_interval', sa.Integer(), nullable=True),
    sa.Column('min_leverage', sa.Numeric(), nullable=False),
    sa.Column('max_leverage', sa.Numeric(), nullable=False),
    sa.Column('leverage_step', sa.Numeric(), nullable=False),
    sa.Column('max_trading_qty', sa.Numeric(), nullable=False),
    sa.Column('min_trading_qty', sa.Numeric(), nullable=False),
    sa.Column('qty_step', sa.Numeric(), nullable=False),
    sa.Column('min_price', sa.Numeric(), nullable=False),
    sa.Column('max_price', sa.Numeric(), nullable=False),
    sa.Column('tick_size', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bybit_linear_perp_instruments_symbol'), 'bybit_linear_perp_instruments', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bybit_linear_perp_instruments_symbol'), table_name='bybit_linear_perp_instruments')
    op.drop_table('bybit_linear_perp_instruments')
    # ### end Alembic commands ###
