"""Initial migration

Revision ID: 624df8e0e995
Revises: 
Create Date: 2024-10-27 16:58:00.589733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '624df8e0e995'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bybit_instruments_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contract_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('base_coin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quote_coin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('launch_time', sa.Integer(), nullable=True),
    sa.Column('delivery_time', sa.Integer(), nullable=True),
    sa.Column('delivery_fee_rate', sa.Numeric(), nullable=True),
    sa.Column('price_scale', sa.Integer(), nullable=False),
    sa.Column('unified_margin_trade', sa.Boolean(), nullable=False),
    sa.Column('funding_interval', sa.Integer(), nullable=True),
    sa.Column('settle_coin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_leverage', sa.Numeric(), nullable=False),
    sa.Column('max_leverage', sa.Numeric(), nullable=False),
    sa.Column('leverage_step', sa.Numeric(), nullable=False),
    sa.Column('max_trading_qty', sa.Numeric(), nullable=False),
    sa.Column('min_trading_qty', sa.Numeric(), nullable=False),
    sa.Column('qty_step', sa.Numeric(), nullable=False),
    sa.Column('min_price', sa.Numeric(), nullable=False),
    sa.Column('max_price', sa.Numeric(), nullable=False),
    sa.Column('tick_size', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bybit_instruments_raw_symbol'), 'bybit_instruments_raw', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bybit_instruments_raw_symbol'), table_name='bybit_instruments_raw')
    op.drop_table('bybit_instruments_raw')
    # ### end Alembic commands ###
