"""add Raw Kline Table

Revision ID: 864c58fbc5c9
Revises: 2feb6c33aa9a
Create Date: 2024-11-03 10:28:24.724637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '864c58fbc5c9'
down_revision: Union[str, None] = '2feb6c33aa9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bybit_linear_perp_kline_5m_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('startTime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('openPrice', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('highPrice', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lowPrice', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('closePrice', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('volume', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turnover', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bybit_linear_perp_kline_5m_raw')
    # ### end Alembic commands ###
