"""create kline 5 min table

Revision ID: 8b1d797caa1f
Revises: 9f6d3fdbe956
Create Date: 2024-11-04 23:22:49.147821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b1d797caa1f'
down_revision: Union[str, None] = '9f6d3fdbe956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bybit_linear_perp_kline_5m',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Numeric(), nullable=False),
    sa.Column('high_price', sa.Numeric(), nullable=False),
    sa.Column('low_price', sa.Numeric(), nullable=False),
    sa.Column('close_price', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('turnover', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'period_start', name='uix_symbol_period_start')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bybit_linear_perp_kline_5m')
    # ### end Alembic commands ###
