"""adding is_processed flag

Revision ID: 9f6d3fdbe956
Revises: 864c58fbc5c9
Create Date: 2024-11-04 21:46:13.191935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9f6d3fdbe956"
down_revision: Union[str, None] = "864c58fbc5c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bybit_linear_perp_kline_5m_raw",
        sa.Column(
            "is_processed", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bybit_linear_perp_kline_5m_raw", "is_processed")
    # ### end Alembic commands ###
