"""add price levels

Revision ID: af872e1a3e86
Revises: e1ffa1d6da1e
Create Date: 2024-12-22 15:36:59.650641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af872e1a3e86'
down_revision: Union[str, None] = 'e1ffa1d6da1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_symbols_price_pivot_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instrument_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timeframe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('lookback_period', sa.Integer(), nullable=False),
    sa.Column('price_level', sa.Numeric(), nullable=False),
    sa.Column('is_support', sa.Boolean(), nullable=False),
    sa.Column('is_resistance', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'symbol', 'instrument_type', 'timeframe', 'period_start', 'lookback_period', name='uix_price_level_symbol_timeframe_period_price')
    )
    op.create_index(op.f('ix_crypto_symbols_price_pivot_levels_exchange'), 'crypto_symbols_price_pivot_levels', ['exchange'], unique=False)
    op.create_index(op.f('ix_crypto_symbols_price_pivot_levels_instrument_type'), 'crypto_symbols_price_pivot_levels', ['instrument_type'], unique=False)
    op.create_index(op.f('ix_crypto_symbols_price_pivot_levels_lookback_period'), 'crypto_symbols_price_pivot_levels', ['lookback_period'], unique=False)
    op.create_index(op.f('ix_crypto_symbols_price_pivot_levels_period_start'), 'crypto_symbols_price_pivot_levels', ['period_start'], unique=False)
    op.create_index(op.f('ix_crypto_symbols_price_pivot_levels_symbol'), 'crypto_symbols_price_pivot_levels', ['symbol'], unique=False)
    op.create_index(op.f('ix_crypto_symbols_price_pivot_levels_timeframe'), 'crypto_symbols_price_pivot_levels', ['timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_symbols_price_pivot_levels_timeframe'), table_name='crypto_symbols_price_pivot_levels')
    op.drop_index(op.f('ix_crypto_symbols_price_pivot_levels_symbol'), table_name='crypto_symbols_price_pivot_levels')
    op.drop_index(op.f('ix_crypto_symbols_price_pivot_levels_period_start'), table_name='crypto_symbols_price_pivot_levels')
    op.drop_index(op.f('ix_crypto_symbols_price_pivot_levels_lookback_period'), table_name='crypto_symbols_price_pivot_levels')
    op.drop_index(op.f('ix_crypto_symbols_price_pivot_levels_instrument_type'), table_name='crypto_symbols_price_pivot_levels')
    op.drop_index(op.f('ix_crypto_symbols_price_pivot_levels_exchange'), table_name='crypto_symbols_price_pivot_levels')
    op.drop_table('crypto_symbols_price_pivot_levels')
    # ### end Alembic commands ###
