"""Add 15M, 1H, 4H, 1d tables

Revision ID: e1ffa1d6da1e
Revises: 8b1d797caa1f
Create Date: 2024-11-10 16:29:01.342326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1ffa1d6da1e'
down_revision: Union[str, None] = '8b1d797caa1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bybit_linear_perp_kline_15m',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Numeric(), nullable=False),
    sa.Column('high_price', sa.Numeric(), nullable=False),
    sa.Column('low_price', sa.Numeric(), nullable=False),
    sa.Column('close_price', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('turnover', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'period_start', name='uix_symbol_period_start_15m')
    )
    op.create_table('bybit_linear_perp_kline_1d',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Numeric(), nullable=False),
    sa.Column('high_price', sa.Numeric(), nullable=False),
    sa.Column('low_price', sa.Numeric(), nullable=False),
    sa.Column('close_price', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('turnover', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'period_start', name='uix_symbol_period_start_1d')
    )
    op.create_table('bybit_linear_perp_kline_1h',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Numeric(), nullable=False),
    sa.Column('high_price', sa.Numeric(), nullable=False),
    sa.Column('low_price', sa.Numeric(), nullable=False),
    sa.Column('close_price', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('turnover', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'period_start', name='uix_symbol_period_start_1h')
    )
    op.create_table('bybit_linear_perp_kline_4h',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Numeric(), nullable=False),
    sa.Column('high_price', sa.Numeric(), nullable=False),
    sa.Column('low_price', sa.Numeric(), nullable=False),
    sa.Column('close_price', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('turnover', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'period_start', name='uix_symbol_period_start_4h')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bybit_linear_perp_kline_4h')
    op.drop_table('bybit_linear_perp_kline_1h')
    op.drop_table('bybit_linear_perp_kline_1d')
    op.drop_table('bybit_linear_perp_kline_15m')
    # ### end Alembic commands ###
