name: Python Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-asyncio pytest-env
        pip install numpy==1.24.3
        pip install -r requirements.txt

    - name: Create test env file
      run: |
        echo "BYBIT_API_KEY=test_key" > .env.test
        echo "BYBIT_API_SECRET=test_secret" >> .env.test
        echo "BYBIT_TESTNET=true" >> .env.test
        echo "DB_CONNECTION_STRING=postgresql://postgres:postgres@localhost:5432/test_db" >> .env.test
        echo "BETTER_STACK_SOURCE_TOKEN=test_token" >> .env.test
        cat .env.test # Print for debugging

    - name: Run tests with pytest
      env:
        BYBIT_API_KEY: test_key
        BYBIT_API_SECRET: test_secret
        BYBIT_TESTNET: "true"
        DB_CONNECTION_STRING: postgresql://postgres:postgres@localhost:5432/test_db
        BETTER_STACK_SOURCE_TOKEN: test_token
      run: |
        pytest tests/ -v --cov=. --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        fail_ci_if_error: true